apiVersion: v1
kind: Service
metadata:
  name: ghostunnel
  labels:
    app: ghostunnel
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 10443
      name: ghostunnel
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: netcat
  selector:
    app: ghostunnel
---
apiVersion: v1
kind: Service
metadata:
  name: netutils
  labels:
    app: netutils
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: netcat
  selector:
    app: netutils